# Generated by Django 4.2.4 on 2023-08-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_category_options_alter_women_options_and_more'),
        ('women', '0003_auto_20210115_1116'),
    ]

    operations = [
    ]
